const prendas = [
    {
        id: 1,
        nombre: 'Bufanda Café',
        precio: 4980,
        imagen: '../assets/img/bufanda-cafe-foto.png',
        tipo: 'accesorios',
        color: 'cafe',
        talle: ['unico'],
    },
    {
        id: 2,
        nombre: 'Tapado Beige',
        precio: 20990,
        imagen: '../assets/img/tapado-beige-foto.png',
        tipo: 'tapados',
        color: 'beige',
        talle: ['M', 'L'],
    },
    {
        id: 3,
        nombre: 'Campera Peluche',
        precio: 18700,
        imagen: '../assets/img/campera-peluche-foto.png',
        tipo: 'camperas',
        color: 'blanco',
        talle: ['S', 'L'],
    },
    {
        id: 4,
        nombre: 'Jean Desgastado',
        precio: 10600,
        imagen: '../assets/img/jean-desgastado-foto.png',
        tipo: 'jeans',
        color: 'azul',
        talle: ['S', 'M'],
    },
    {
        id: 5,
        nombre: 'Botas Negras',
        precio: 12800,
        imagen: '../assets/img/botas-negras-foto.png',
        tipo: 'calzado',
        color: 'negro',
        talle: ['unico'],
    },
    {
        id: 6,
        nombre: 'Jean Blanco',
        precio: 11700,
        imagen: '../assets/img/jean-blanco-foto.png',
        tipo: 'jeans',
        color: 'blanco',
        talle: ['M', 'L'],
    }
];
